### ISSUE TITLE
Wallet_secret cli.py error

### ISSUE THREAD

**Issue by ghost** [theQRL/QRL#1149]
when running wallet_secret:

```
Traceback (most recent call last):
  File "cli.py", line 878, in <module>
    main()
  File "cli.py", line 874, in main
    qrl()
  File "/home/owner/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/owner/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/owner/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/owner/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/owner/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/owner/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "cli.py", line 285, in wallet_secret
    click.echo('Wallet Address  : %s' % (address_item.qaddress))
AttributeError: 'AddressItem' object has no attribute 'qaddress'
```

**Comment by cyyber** [comment]
Fixed in PR #1151 . will be available on next release.
