### ISSUE TITLE
Problem installing (updating) QRL client

### ISSUE THREAD

**Issue by jonlindg** [theQRL/QRL#1169]
I followed the documentation to update my QRL client to the newest version:
```
sudo apt update && sudo apt upgrade -y
sudo apt-get -y install swig3.0 python3-dev python3-pip build-essential cmake pkg-config libssl-dev libffi-dev libhwloc-dev libboost-dev
sudo pip3 install -U qrl
```

The installation fails, with error message:

```
Found existing installation: pyqryptonight 0.7.2
    Uninstalling pyqryptonight-0.7.2:
      Successfully uninstalled pyqryptonight-0.7.2
  Running setup.py install for pyqryptonight ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7qmn6nz6/pyqryptonight/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-82le_12a-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/pyqryptonight
    copying pyqryptonight/__init__.py -> build/lib.linux-x86_64-3.5/pyqryptonight
    copying pyqryptonight/pyqryptonight.py -> build/lib.linux-x86_64-3.5/pyqryptonight
    running build_ext
    -- The C compiler identification is GNU 5.4.0
    -- The CXX compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- BUILD_TESTS    OFF
    -- GOLANG WRAPPER OFF
    -- PYTHON WRAPPER ON
    -- WEBASSEMBLY    OFF
    -- Found SWIG: /usr/bin/swig3.0 (found version "3.0.8")
    CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
      Unable to find the requested Boost libraries.
    
      Boost version: 1.54.0
    
      Boost include path: /usr/local/include
    
      Detected version of Boost is too old.  Requested version was 1.58 (or
      newer).
    Call Stack (most recent call first):
      CMakeLists.txt:36 (FIND_PACKAGE)
    
    
    -- Python wrapper enabled
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found suitable version "3.5.2", minimum required is "3.4")
    -- CMAKE_SWIG_OUTDIR: /tmp/pip-build-7qmn6nz6/pyqryptonight/build/lib.linux-x86_64-3.5/pyqryptonight
    -- CMAKE_LIBRARY_OUTPUT_DIRECTORY: /tmp/pip-build-7qmn6nz6/pyqryptonight/build/lib.linux-x86_64-3.5/pyqryptonight
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-build-7qmn6nz6/pyqryptonight/build/temp.linux-x86_64-3.5/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7qmn6nz6/pyqryptonight/setup.py", line 71, in <module>
        setup_package()
      File "/tmp/pip-build-7qmn6nz6/pyqryptonight/setup.py", line 67, in setup_package
        use_pyscaffold=True)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-7qmn6nz6/pyqryptonight/setup.py", line 43, in run
        subprocess.check_call(cmake_call, cwd=self.build_temp, env=env)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-build-7qmn6nz6/pyqryptonight', '-DBUILD_PYTHON=ON', '-DBUILD_TESTS=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-build-7qmn6nz6/pyqryptonight/build/lib.linux-x86_64-3.5', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
    
    ----------------------------------------
  Rolling back uninstall of pyqryptonight
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7qmn6nz6/pyqryptonight/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-82le_12a-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-7qmn6nz6/pyqryptonight/
````

QRL Command Line Interface version: 0.61.3
pip3 version: 9.0.3
python3 version: 3.5.2
Ubuntu 16.04 LTS

Edit: gcc/g++ version is 5.4.0
```
>>g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
>>gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

```

**Comment by jonlindg** [comment]
Uninstalled qrl and then tried again, still have the same issue.

**Comment by jleni** [comment]
It seems to be related to the boost version you have
> Boost version: 1.54.0
> Detected version of Boost is too old.  Requested version was 1.58

It is strange we have not seen this is integration tests.

**Comment by jonlindg** [comment]
The issue is that I have two boost installed, one in usr/local/include and one in usr/include. Typing 
`dpkg -s libboost-dev | grep 'Version'`
gives me version 1.58 (which is the usr/include version), and if I try to upgrade it is going to tell me I have the latest version. However, when installing qrl, cmake instead finds the /usr/local/include version and thus complains.

Setting the environmental variable BOOST_ROOT to a different path does not make a difference, I would probably need to pass a flag to cmake that sets the proper oost path, but since cmake is run by the pip3 install command I am not sure how to do that.

**Comment by jonlindg** [comment]
I solved the issue, although I am not sure this is the recommended method. I modified the FindBoost.cmake file, and added
`set(ENV{BOOST_ROOT} "/usr/include")`

This will make sure that cmake finds the correct version of boost.

**Comment by jleni** [comment]
This is actually a qryptonight issue. I will open an issue in qryptonight and reference this one.
