### ISSUE TITLE
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by happysmash27** [theQRL/QRL#1617]
**Describe the bug**
When launching QRL_start, the following error occurs: 

```
Traceback (most recent call last):
  File "/home/happysmash27/.local/bin/qrl_start", line 11, in <module>
    sys.exit(main())
  File "/home/happysmash27/.local/lib64/python3.5/site-packages/qrl/main.py", line 143, in main
    qrlnode = QRLNode(mining_address=mining_address)
  File "/home/happysmash27/.local/lib64/python3.5/site-packages/qrl/core/qrlnode.py", line 36, in __init__
    self.peer_manager = P2PPeerManager()
  File "/home/happysmash27/.local/lib64/python3.5/site-packages/qrl/core/p2p/p2pPeerManager.py", line 40, in __init__
    filename=self.banned_peers_filename)
  File "/home/happysmash27/.local/lib64/python3.5/site-packages/qrl/core/misc/expiring_set.py", line 17, in __init__
    self._load()
  File "/home/happysmash27/.local/lib64/python3.5/site-packages/qrl/core/misc/expiring_set.py", line 62, in _load
    self._data = json.load(f)
  File "/home/happysmash27/.local/lib64/python3.5/site-packages/simplejson/__init__.py", line 461, in load
    use_decimal=use_decimal, **kw)
  File "/home/happysmash27/.local/lib64/python3.5/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/happysmash27/.local/lib64/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/happysmash27/.local/lib64/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
This is the only output. 

**To Reproduce**
1. Launch qrl_start

**Expected behavior**
qrl_start runs. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Version:  1.1.11 python

**Comment by happysmash27** [comment]
I'm not sure what happened here, but updating doesn't seem to help.

**Comment by cyyber** [comment]
remove ~/.qrl/banned_peers.qrl

**Comment by happysmash27** [comment]
Thank you very much! Everything works now.
