### ISSUE TITLE
GetAddressState not returning result for a specific testnet address

### ISSUE THREAD

**Issue by som-dev** [theQRL/QRL#1667]
Running testnet qrl 0.2.0

Call to Public API GetAddressState for Q0104004d40a781b697e69f7e806d0158acb9e8e0566a05dc06744756d81fc08b256ca4cbf7f0e3
returns an exception:
  File "/home/username/.local/lib/python3.6/site-packages/grpc/_channel.py", line 487, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/home/username/.local/lib/python3.6/site-packages/grpc/_channel.py", line 437, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, 'NoneType' object has no attribute 'balance')>

On my server node I see the following error at the time of the query:
2020-03-01 13:12:26,614|0.2.0 python|synced  |ThreadPoolExecutor-0_0| ERROR : Traceback (most recent call last):
  File "/home/username/.local/lib/python3.6/site-packages/qrl/services/grpcHelper.py", line 25, in wrap_f
    return f(caller_self, request, context)
  File "/home/username/.local/lib/python3.6/site-packages/qrl/services/PublicAPIService.py", line 109, in GetAddressState
    address_state = self.qrlnode.get_address_state(request.address)
  File "/home/username/.local/lib/python3.6/site-packages/qrl/core/qrlnode.py", line 379, in get_address_state
    address_state = self._chain_manager.get_address_state(address)
  File "/home/username/.local/lib/python3.6/site-packages/qrl/core/ChainManager.py", line 136, in get_address_state
    tokens[token_txn_hash] = token_balance.balance
AttributeError: 'NoneType' object has no attribute 'balance'

I believe it is related to txhash 4fb7afe2f59ebc121321f8e8296879f8a7e59db99c57e320d0266fe166c85908

Curiously, I cannot query this address on the testnet explorer website either. The web page keeps spinning.

**Comment by cyyber** [comment]
Thanks for reporting. Issue has been fixed in PR #1670 
Fix will be available on next release.
