### ISSUE TITLE
0.51.x telnet command "send"

### ISSUE THREAD

**Issue by FL-Riko** [theQRL/QRL#309]
send 0 0 10 0 lead to an error

**Comment by FL-Riko** [comment]
Fat fingers error, hit the wrong button and closed the ticket
Error occurs shortly before block 3800, before my node create one successfully stake

**Comment by jleni** [comment]
@randomshinichi It is possible that PR #325 fixed this problem

**Comment by randomshinichi** [comment]
Nope, not fixed

**Comment by jleni** [comment]
Adding call stack:

2017-10-05 18:01:05,316 |syncing| ERROR : get_stxn_state blocknum not found in blocks 4266
2017-10-05 18:01:05,317 |syncing| CRITICAL : [TWISTED] Unhandled Error
Traceback (most recent call last):
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/lenij/crypto/QRL/qrl/core/walletprotocol.py", line 97, in dataReceived
    if not self.parse_cmd(data):
  File "/home/lenij/crypto/QRL/qrl/core/walletprotocol.py", line 78, in parse_cmd
    self.cmd_mapping[command](args)
  File "/home/lenij/crypto/QRL/qrl/core/walletprotocol.py", line 320, in _send
    addr=tx.txfrom)
  File "/home/lenij/crypto/QRL/qrl/core/ChainBuffer.py", line 365, in get_stxn_state
    self.error_msg('get_stxn_state', blocknumber)
  File "/home/lenij/crypto/QRL/qrl/core/ChainBuffer.py", line 626, in error_msg
    logger.error('Min block num %s', min(self.blocks))
builtins.ValueError: min() arg is an empty sequence

Unhandled Error
Traceback (most recent call last):
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/home/lenij/anaconda3/envs/qrl3/lib/python3.6/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/lenij/crypto/QRL/qrl/core/walletprotocol.py", line 97, in dataReceived
    if not self.parse_cmd(data):
  File "/home/lenij/crypto/QRL/qrl/core/walletprotocol.py", line 78, in parse_cmd
    self.cmd_mapping[command](args)
  File "/home/lenij/crypto/QRL/qrl/core/walletprotocol.py", line 320, in _send
    addr=tx.txfrom)
  File "/home/lenij/crypto/QRL/qrl/core/ChainBuffer.py", line 365, in get_stxn_state
    self.error_msg('get_stxn_state', blocknumber)
  File "/home/lenij/crypto/QRL/qrl/core/ChainBuffer.py", line 626, in error_msg
    logger.error('Min block num %s', min(self.blocks))
builtins.ValueError: min() arg is an empty sequence

**Comment by jleni** [comment]
At least the crash I had seems like an easy fix. While the node is syncing, self.blocks is empty.
wallet should not allow sending until the node is in sync.

**Comment by jleni** [comment]
reducing the priority. Telnet interface will be soon deprecated. In the next few weeks the recommend approach is to use the webwallet. A new CLI based on grpc will be available soon.

**Comment by cyyber** [comment]
Telnet client has been replaced by command line client.
