### ISSUE TITLE
Crtitical Error withTwisted lib

### ISSUE THREAD

**Issue by FL-Riko** [theQRL/QRL#310]
2017-10-01 19:06:28,173 |synced| INFO : 104.251.219.215 peers data received: ['104.237.3.184', '104.251.219.145', '104.237.3.185', '104.251.219.40', '187.205.233.48', '75.8.77.11', '74.104.141.84', '108.226.196.132', '108.233.73.175', '192.222.211.183', '162.195.105.154', '187.149.33.128', '94.102.63.214', '91.7.178.160', '185.148.185.1'] 2017-10-01 19:06:28,332 |synced| INFO : >>>Blockheight from: 104.251.219.215 blockheight: 3699 local blockheight: 3799 1506877588.331957 2017-10-01 19:06:28,335 |synced| INFO : genesis pos countdown to block 1 begun, 60s until stake tx circulated.. 2017-10-01 19:06:28,340 |synced| INFO : 104.251.219.215 version: 0.52.1a | genesis prev_headerhash Cross-Breed-Testnet 2017-10-01 19:06:29,340 |synced| INFO : pre_pos_1 2017-10-01 19:06:29,365 |synced| CRITICAL : [TWISTED] Unhandled Error Traceback (most recent call last): File "start_qrl.py", line 13, in <module> main() File "/home/pi/QRL/qrl/main.py", line 124, in main reactor.run() File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 1243, in run self.mainLoop() File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 1252, in mainLoop self.runUntilCurrent() --- <exception caught here> --- File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent call.func(*call.args, **call.kw) File "/home/pi/QRL/qrl/core/node.py", line 170, in pre_pos_1 if self.chain.mining_address not in self.chain.m_blockchain[0].stake_list: builtins.AttributeError: 'Block' object has no attribute 'stake_list'

**Comment by cyyber** [comment]
Fixed in PR #314
