### ISSUE TITLE
"No package 'libffi' found" error during "pip3 install -r requirements.txt" on Raspberry Pi3

### ISSUE THREAD

**Issue by converghub** [theQRL/QRL#312]
When I tried to `sudo pip3 install -r requirements.txt` , I got an error saying "Package libffi was not found." 
RP3 users should install libffi-dev, like `$ sudo apt-get install libffi-dev` IMO.

Logs are followings:
```
pi@raspberrypi:~/QRL $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.1 (stretch)
Release:        9.1
Codename:       stretch
pi@raspberrypi:~/QRL $ uname -a
Linux raspberrypi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux
```
```
pi@raspberrypi:~/QRL $ sudo pip3 install -r requirements.txt
Requirement already satisfied: jsonpickle>=0.9.5 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: leveldb>=0.19 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: statistics>=1.0.3.5 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: ntplib>=0.3.3 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: Twisted==17.5.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: colorlog>=3.0.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: simplejson>=3.11.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: PyYAML==3.12 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 9))
Collecting service_identity (from -r requirements.txt (line 10))
  Using cached service_identity-17.0.0-py2.py3-none-any.whl
Collecting pyopenssl>=17.3.0 (from -r requirements.txt (line 11))
  Using cached pyOpenSSL-17.3.0-py2.py3-none-any.whl
Requirement already satisfied: pyqrllib>=0.1.20 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied: docutils>=0.3 in /usr/local/lib/python3.5/dist-packages (from statistics>=1.0.3.5->-r requirements.txt (line 4))
Requirement already satisfied: constantly>=15.1 in /usr/local/lib/python3.5/dist-packages (from Twisted==17.5.0->-r requirements.txt (line 6))
Requirement already satisfied: zope.interface>=4.0.2 in /usr/local/lib/python3.5/dist-packages (from Twisted==17.5.0->-r requirements.txt (line 6))
Requirement already satisfied: Automat>=0.3.0 in /usr/local/lib/python3.5/dist-packages (from Twisted==17.5.0->-r requirements.txt (line 6))
Requirement already satisfied: incremental>=16.10.1 in /usr/local/lib/python3.5/dist-packages (from Twisted==17.5.0->-r requirements.txt (line 6))
Requirement already satisfied: hyperlink>=17.1.1 in /usr/local/lib/python3.5/dist-packages (from Twisted==17.5.0->-r requirements.txt (line 6))
Requirement already satisfied: attrs in /usr/local/lib/python3.5/dist-packages (from service_identity->-r requirements.txt (line 10))
Requirement already satisfied: pyasn1-modules in /usr/local/lib/python3.5/dist-packages (from service_identity->-r requirements.txt (line 10))
Requirement already satisfied: pyasn1 in /usr/lib/python3/dist-packages (from service_identity->-r requirements.txt (line 10))
Collecting cryptography>=1.9 (from pyopenssl>=17.3.0->-r requirements.txt (line 11))
  Using cached cryptography-2.0.3.tar.gz
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from pyopenssl>=17.3.0->-r requirements.txt (line 11))
Requirement already satisfied: scikit-build in /usr/local/lib/python3.5/dist-packages (from pyqrllib>=0.1.20->-r requirements.txt (line 12))
Requirement already satisfied: setuptools in /usr/local/lib/python3.5/dist-packages (from zope.interface>=4.0.2->Twisted==17.5.0->-r requirements.txt (line 6))
Requirement already satisfied: idna>=2.1 in /usr/lib/python3/dist-packages (from cryptography>=1.9->pyopenssl>=17.3.0->-r requirements.txt (line 11))
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python3.5/dist-packages (from cryptography>=1.9->pyopenssl>=17.3.0->-r requirements.txt (line 11))
Collecting cffi>=1.7 (from cryptography>=1.9->pyopenssl>=17.3.0->-r requirements.txt (line 11))
  Using cached cffi-1.11.0.tar.gz
Requirement already satisfied: wheel>=0.29.0 in /usr/local/lib/python3.5/dist-packages (from scikit-build->pyqrllib>=0.1.20->-r requirements.txt (line 12))
Requirement already satisfied: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.7->cryptography>=1.9->pyopenssl>=17.3.0->-r requirements.txt (line 11))
Building wheels for collected packages: cryptography, cffi
  Running setup.py bdist_wheel for cryptography ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vsmjkw98/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp9_g1_6xopip-wheel- --python-tag cp35:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  c/_cffi_backend.c:15:17: fatal error: ffi.h: そのようなファイルやディレクトリはありません
   #include <ffi.h>
                   ^
  compilation terminated.
  Traceback (most recent call last):
    File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
      extra_postargs)
    File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
      spawn(cmd, dry_run=self.dry_run)
    File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
      _spawn_posix(cmd, search_path, dry_run=dry_run)
    File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
      % (cmd, exit_status))
  distutils.errors.DistutilsExecError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/bdist_egg.py", line 169, in run
      cmd = self.call_command('install_lib', warn_dir=0)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/bdist_egg.py", line 155, in call_command
      self.run_command(cmdname)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/install_lib.py", line 11, in run
      self.build()
    File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
      self.run_command('build_ext')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/build_ext.py", line 75, in run
      _build_ext.run(self)
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/build_ext.py", line 196, in build_extension
      _build_ext.build_extension(self, ext)
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 533, in build_extension
      depends=ext.depends)
    File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
      self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
      raise CompileError(msg)
  distutils.errors.CompileError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 158, in save_modules
      yield saved
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 199, in setup_context
      yield
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 254, in run_setup
      _execfile(setup_script, ns)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 49, in _execfile
      exec(code, globals, locals)
    File "/tmp/easy_install-31x93kpv/cffi-1.11.0/setup.py", line 235, in <module>

    File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
      raise SystemExit("error: " + str(msg))
  SystemExit: error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1104, in run_setup
      run_setup(setup_script, args)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 257, in run_setup
      raise
    File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
      self.gen.throw(type, value, traceback)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 199, in setup_context
      yield
    File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
      self.gen.throw(type, value, traceback)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 170, in save_modules
      saved_exc.resume()
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 145, in resume
      six.reraise(type, exc, self._tb)
    File "/usr/local/lib/python3.5/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
      raise value.with_traceback(tb)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 158, in save_modules
      yield saved
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 199, in setup_context
      yield
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 254, in run_setup
      _execfile(setup_script, ns)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 49, in _execfile
      exec(code, globals, locals)
    File "/tmp/easy_install-31x93kpv/cffi-1.11.0/setup.py", line 235, in <module>

    File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
      raise SystemExit("error: " + str(msg))
  SystemExit: error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-vsmjkw98/cryptography/setup.py", line 312, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 335, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 456, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 863, in resolve
      replace_conflicting=replace_conflicting
    File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1141, in best_match
      return self.obtain(req, installer)
    File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1153, in obtain
      return installer(requirement)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 522, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 672, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 698, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 879, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1106, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vsmjkw98/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  c/_cffi_backend.c:15:17: fatal error: ffi.h: そのようなファイルやディレクトリはありません
   #include <ffi.h>
                   ^
  compilation terminated.
  Traceback (most recent call last):
    File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
      extra_postargs)
    File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
      spawn(cmd, dry_run=self.dry_run)
    File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
      _spawn_posix(cmd, search_path, dry_run=dry_run)
    File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
      % (cmd, exit_status))
  distutils.errors.DistutilsExecError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/bdist_egg.py", line 169, in run
      cmd = self.call_command('install_lib', warn_dir=0)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/bdist_egg.py", line 155, in call_command
      self.run_command(cmdname)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/install_lib.py", line 11, in run
      self.build()
    File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
      self.run_command('build_ext')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/build_ext.py", line 75, in run
      _build_ext.run(self)
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/build_ext.py", line 196, in build_extension
      _build_ext.build_extension(self, ext)
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 533, in build_extension
      depends=ext.depends)
    File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
      self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
      raise CompileError(msg)
  distutils.errors.CompileError: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 158, in save_modules
      yield saved
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 199, in setup_context
      yield
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 254, in run_setup
      _execfile(setup_script, ns)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 49, in _execfile
      exec(code, globals, locals)
    File "/tmp/easy_install-hvqq8nwp/cffi-1.11.0/setup.py", line 235, in <module>

    File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
      raise SystemExit("error: " + str(msg))
  SystemExit: error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1104, in run_setup
      run_setup(setup_script, args)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 257, in run_setup
      raise
    File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
      self.gen.throw(type, value, traceback)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 199, in setup_context
      yield
    File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
      self.gen.throw(type, value, traceback)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 170, in save_modules
      saved_exc.resume()
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 145, in resume
      six.reraise(type, exc, self._tb)
    File "/usr/local/lib/python3.5/dist-packages/pkg_resources/_vendor/six.py", line 685, in reraise
      raise value.with_traceback(tb)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 158, in save_modules
      yield saved
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 199, in setup_context
      yield
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 254, in run_setup
      _execfile(setup_script, ns)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 49, in _execfile
      exec(code, globals, locals)
    File "/tmp/easy_install-hvqq8nwp/cffi-1.11.0/setup.py", line 235, in <module>

    File "/usr/lib/python3.5/distutils/core.py", line 163, in setup
      raise SystemExit("error: " + str(msg))
  SystemExit: error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-vsmjkw98/cryptography/setup.py", line 312, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 335, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 456, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 863, in resolve
      replace_conflicting=replace_conflicting
    File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1141, in best_match
      return self.obtain(req, installer)
    File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1153, in obtain
      return installer(requirement)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 522, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 672, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 698, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 879, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/command/easy_install.py", line 1106, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  ----------------------------------------
  Failed cleaning build dir for cryptography
  Running setup.py bdist_wheel for cffi ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vsmjkw98/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp0wt6b0lopip-wheel- --python-tag cp35:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.5
  creating build/lib.linux-armv7l-3.5/cffi
  copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/__init__.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/error.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/recompiler.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/commontypes.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/cparser.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/vengine_gen.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/lock.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/ffiplatform.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/model.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/api.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/verifier.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/_cffi_include.h -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/parse_c_type.h -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/_embedding.h -> build/lib.linux-armv7l-3.5/cffi
  copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-3.5/cffi
  running build_ext
  building '_cffi_backend' extension
  creating build/temp.linux-armv7l-3.5
  creating build/temp.linux-armv7l-3.5/c
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-RUbMX3/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.5m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.5/c/_cffi_backend.o
  c/_cffi_backend.c:15:17: fatal error: ffi.h: そのようなファイルやディレクトリはありません
   #include <ffi.h>
                   ^
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cffi
  Running setup.py clean for cffi
Failed to build cryptography cffi
Installing collected packages: cffi, cryptography, pyopenssl, service-identity
  Running setup.py install for cffi ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vsmjkw98/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lrxmya2_-record/install-record.txt --single-version-externally-managed --compile:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.5
    creating build/lib.linux-armv7l-3.5/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/__init__.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/error.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/recompiler.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/commontypes.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/cparser.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/lock.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/model.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/api.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/verifier.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/_embedding.h -> build/lib.linux-armv7l-3.5/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-3.5/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-armv7l-3.5
    creating build/temp.linux-armv7l-3.5/c
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-RUbMX3/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.5m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.5/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: そのようなファイルやディレクトリはありません
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vsmjkw98/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lrxmya2_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vsmjkw98/cffi/
```

**Comment by jleni** [comment]
Thanks @converghub for opening this issue! 
This had already been corrected and libffi-dev is already included in the instructionsf for raspberry pi.
