### ISSUE TITLE
telnet "search" closing connection | CRITICAL : [TWISTED] Unhandled Error

### ISSUE THREAD

**Issue by fr1t2** [theQRL/QRL#318]
searching for Q'address in telnet gives CRITICAL : [TWISTED] Unhandled Error | 'Chain' object has no attribute 'search_txhash' 

$ telnet localhost 2000

getinfo
>>> Version: 0.52.2a
>>> Uptime: 30799.47098827362
>>> Nodes connected: 7
>>> Staking set to: True
>>> Sync status: synced

search Q3605e34c94ca833a2d6e80137eb11414abace2723e5ad7b61d3c954b85c90741bdae01da
Connection closed by foreign host.
---------------------------~/.qrl/qrl.log -------------------------------------

2017-10-02 23:06:45,962 |synced| INFO : [ChainBuffer] Block #6193 added  stake: Qd72b34429cc1efde3721a80f06b9d5755034a49f49c1c551f0843a8e7dd12275cecb6398
2017-10-02 23:06:58,667 |synced| INFO : >>> new local connection 1 IPv4Address(TCP, '127.0.0.1', 56192)
2017-10-02 23:07:28,302 |synced| CRITICAL : [TWISTED] Unhandled Error
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/ubuntu/QRL/qrl/core/walletprotocol.py", line 340, in dataReceived
    if not self.parse_cmd(self.parse(data)):
  File "/home/ubuntu/QRL/qrl/core/walletprotocol.py", line 107, in parse_cmd
    tmp_output = json.loads(self.factory.chain.search_txhash(args[0]))
builtins.AttributeError: 'Chain' object has no attribute 'search_txhash'

2017-10-02 23:07:29,976 |synced| INFO : create_new_block #6194
2017-10-02 23:07:29,991 |synced| INFO : BLOCK: 6191 epoch: 61 blocks_left: 8 nonce: 19 stake_selector Q321551228be4c8275bc3a2665347f4b399216268bf6a704c6fd5ced5666c117105f82613
2017-10-02 23:07:29,996 |synced| INFO : 68510366c570251670db75b083dcc819d74366325381e5729fead75c4fb233d6 1 tx passed verification.
2017-10-02 23:07:30,138 |synced| INFO : [ChainBuffer] Block #6194 added  stake: Q3605e34c94ca833a2d6e80137eb11414abace2723e5ad7b61d3c954b85c90741bdae01da
2017-10-02 23:07:30,741 |synced| INFO : >>>Received block from 104.237.3.185:9000 6194 Q871011bfa3d8fb9e41c8b59904a116c31a028bab1eadcf5711e64b3445869034d6769cab
2017-10-02 23:07:30,898 |synced| INFO : [ChainBuffer] Block #6194 added  stake: Q871011bfa3d8fb9e41c8b59904a116c31a028bab1eadcf5711e64b3445869034d6769cab

**Comment by jleni** [comment]
@randomshinichi It is possible that PR #325 fixed this problem

**Comment by randomshinichi** [comment]
Nope, it hasn't...

**Comment by jleni** [comment]
Fixed in PR #345
