### ISSUE TITLE
recoverfromhexseed gives CRITICAL : [TWISTED] Unhandled Error

### ISSUE THREAD

**Issue by fr1t2** [theQRL/QRL#320]
Attempting to recover a wallet from hex seed gives the following error in telnet:

ubuntu@ip-172-31-23-129:~$ telnet localhost 2000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
QRL node connection established. Try starting with "help" getinfo
>>> Version: 0.52.2a
>>> Uptime: 116.62990045547485
>>> Nodes connected: 8
>>> Staking set to: True
>>> Sync status: synced
recoverfromhexseed 821cfa30e31b29beab2fd46fdca3d1495a6f29152887c668fa7f49fb9fca74852da675108ca37571010504bb1106e9c4
Connection closed by foreign host.

and in ~/.qrl/qrl.log output:

2017-10-02 23:22:03,947 |synced| INFO : >>> new local connection 1 IPv4Address(TCP, '127.0.0.1', 56234)
2017-10-02 23:22:25,761 |synced| INFO : >>>Received block from 104.251.219.215:9000 6213 Qada446e9ac25b11299e0615de8bd1b7f5404ce0052fbb27db7ada425904a5aea6063deb3
2017-10-02 23:22:25,766 |synced| INFO : BLOCK: 6210 epoch: 62 blocks_left: 89 nonce: 2 stake_selector Q7999ca133d82209ca4a3ad017998e7939d0422eea6cf4c9dac967dd76f2231556be4b56b
2017-10-02 23:22:25,769 |synced| INFO : 7de2798832f2cf90c27090ce7b62f983c7ebeae5d7713eb374d5c039e72acc62 1 tx passed verification.
2017-10-02 23:22:25,911 |synced| INFO : [ChainBuffer] Block #6213 added  stake: Qada446e9ac25b11299e0615de8bd1b7f5404ce0052fbb27db7ada425904a5aea6063deb3
2017-10-02 23:22:54,490 |synced| CRITICAL : [TWISTED] Unhandled Error
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/ubuntu/QRL/qrl/core/walletprotocol.py", line 340, in dataReceived
    if not self.parse_cmd(self.parse(data)):
  File "/home/ubuntu/QRL/qrl/core/walletprotocol.py", line 160, in parse_cmd
    if not args or not hexseed_to_seed(args[0]):
  File "/home/ubuntu/QRL/qrl/core/walletprotocol.py", line 21, in hexseed_to_seed
    return hstr2bin(hex_seed)
builtins.TypeError: in method 'hstr2bin', argument 1 of type 'std::string const &'

**Comment by fr1t2** [comment]
same issue when attempting to `recoverfromwords` is issued into telnet session

qrl.log reads this error:

2017-10-02 23:34:39,080 |synced| CRITICAL : [TWISTED] Unhandled Error
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/ubuntu/QRL/qrl/core/walletprotocol.py", line 340, in dataReceived
    if not self.parse_cmd(self.parse(data)):
  File "/home/ubuntu/QRL/qrl/core/walletprotocol.py", line 190, in parse_cmd
    args = ' '.join(args)
builtins.TypeError: sequence item 0: expected str instance, bytes found

**Comment by jleni** [comment]
@randomshinichi It is possible that PR #325 fixed this problem

**Comment by randomshinichi** [comment]
While testing out the commands around the time that this issue was filed, I never encountered this problem.

Hmm, it certainly fails on master currently, but it works in my branch. Must've been introduced in some commit in between. Anyway it's gone now...

```
Escape character is '^]'.
QRL node connection established. Try starting with "help" recoverfromhexseed 821cfa30e31b29beab2fd46fdca3d1495a6f29152887c668fa7f49fb9fca74852da675108ca37571010504bb1106e9c4
>>> Recovery address: Q3605e34c94ca833a2d6e80137eb11414abace2723e5ad7b61d3c954b85c90741bdae01da
>>> Recovery seed phrase: lofty soil cough cow church tribe coral enemy surge dinghy evade plate chop fled many hasty wife vision wise woods jargon fleshy plague finite mid darwin injury baker ahead raid alpha oral
>>> hexSEED confirm: 821cfa30e31b29beab2fd46fdca3d1495a6f29152887c668fa7f49fb9fca74852da675108ca37571010504bb1106e9c4
>>> savenewaddress if Qaddress matches expectations..

```

**Comment by jleni** [comment]
I am closing now. We reopen or someone will create another issue if reappears
