### ISSUE TITLE
control - C on telnet sessions gives |synced| CRITICAL : [TWISTED] Unhandled Error

### ISSUE THREAD

**Issue by jupiter126** [theQRL/QRL#322]
2017-10-03 11:34:34,916 |synced| CRITICAL : [TWISTED] Unhandled Error
Traceback (most recent call last):    
  File "/home/jupiter/miniconda3/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger return callWithContext({"system": lp}, func, *args, **kw)                                                                                                      
  File "/home/jupiter/miniconda3/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/jupiter/miniconda3/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/jupiter/miniconda3/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext return func(*args,**kw)
--- <exception caught here> ---
File "/home/jupiter/miniconda3/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite why = selectable.doRead()                                                                                                                                       File "/home/jupiter/miniconda3/lib/python3.6/site-packages/twisted/internet/tcp.py", line 208, in doRead 
File "/home/jupiter/miniconda3/lib/python3.6/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived rval = self.protocol.dataReceived(data)                                                                                                                         File "/home/jupiter/Downloads/ethereum/qrl/qrl/core/walletprotocol.py", line 340, in dataReceived if not self.parse_cmd(self.parse(data)):                                                                                                                        
File "/home/jupiter/Downloads/ethereum/qrl/qrl/core/walletprotocol.py", line 57, in parse_cmd if command.decode('utf-8') in self.cmd_list:
builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by jleni** [comment]
This is not applicable anymore. Telnet service has been removed.
