### ISSUE TITLE
0.52.2a wallet command crashes again, leads to block rejected

### ISSUE THREAD

**Issue by FL-Riko** [theQRL/QRL#336]
fresh codebase git pull
command wallet during sync leads to following new error
shortly after a block was rejected

2017-10-07 18:17:26,965 |syncing| INFO : <<<Fetching block: 120 from 104.237.3.185:9000
2017-10-07 18:17:27,096 |syncing| CRITICAL : [TWISTED] Unhandled Error
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/pi/QRL/qrl/core/walletprotocol.py", line 97, in dataReceived
    if not self.parse_cmd(data):
  File "/home/pi/QRL/qrl/core/walletprotocol.py", line 78, in parse_cmd
    self.cmd_mapping[command](args)
  File "/home/pi/QRL/qrl/core/walletprotocol.py", line 344, in _wallet
    self.factory.state.state_read_chain(self.factory.chain)
  File "/home/pi/QRL/qrl/core/state.py", line 486, in state_read_chain
    c = chain.m_get_block(0).state
  File "/home/pi/QRL/qrl/core/chain.py", line 481, in m_get_block
    return self.load_from_file(n)
  File "/home/pi/QRL/qrl/core/chain.py", line 665, in load_from_file
    pos, size = pos_size.decode('utf-8').split(',')
builtins.ValueError: too many values to unpack (expected 2)

2017-10-07 18:17:27,407 |syncing| INFO : >>> Received Block #120

BLOCK reject error:
2017-10-07 18:17:27,407 |syncing| INFO : >>> Received Block #120
2017-10-07 18:17:27,497 |syncing| INFO : BLOCK: 120 epoch: 1 blocks_left: 79 nonce: 2 stake_selector Q871011bfa3d8fb9e41c8b59904a116c31a028bab1eadcf5711e64b3445869034d6769cab
2017-10-07 18:17:27,503 |syncing| INFO : d08c3daa75a524eaeee2e3da04e8c0db98f7400089bab839a1520117c5e710da 1 tx passed verification.
2017-10-07 18:17:27,521 |syncing| ERROR : block rejected - unable to decode serialised data 104.237.3.185
2017-10-07 18:17:27,544 |syncing| ERROR : Traceback (most recent call last):
  File "/home/pi/QRL/qrl/core/p2pprotocol.py", line 430, in PB
    if not self.factory.chain.add_block_mainchain(block):
  File "/home/pi/QRL/qrl/core/chain.py", line 465, in add_block_mainchain
    validate=validate)
  File "/home/pi/QRL/qrl/core/ChainBuffer.py", line 190, in add_block_mainchain
    chain.update_tx_metadata(block)
  File "/home/pi/QRL/qrl/core/chain.py", line 447, in update_tx_metadata
    self.update_txn_count(txn.txto, txn.txfrom)
  File "/home/pi/QRL/qrl/core/chain.py", line 429, in update_txn_count
    self.state.db.put('txn_count_' + txto, last_count + 1)
TypeError: can only concatenate list (not "int") to list

2017-10-07 18:18:04,468 |syncing| WARNING : verify_BK_hash Failed due to prevheaderhash mismatch, blockslen 0

**Comment by jleni** [comment]
Thanks FL-Riko. I was looking at that problem right now.

**Comment by jleni** [comment]
This problem is fixed by PR #339
