### ISSUE TITLE
ERROR : executing [BK] KeyError: 'Qe...'

### ISSUE THREAD

**Issue by jleni** [theQRL/QRL#348]
2017-10-09 07:57:23,882 |synced| INFO : >>>Received block from 104.251.219.215:9000 18203 Qada446e9ac25b11299e0615de8bd1b7f5404ce0052fbb27db7ada425904a5aea6063deb3
2017-10-09 07:57:23,887 |synced| ERROR : executing [BK]
2017-10-09 07:57:23,891 |synced| ERROR : Traceback (most recent call last):
  File "/home/lenij/crypto/QRL/qrl/core/p2pprotocol.py", line 75, in parse_msg
    func(jdata['data'])
  File "/home/lenij/crypto/QRL/qrl/core/p2pprotocol.py", line 340, in BK
    self.factory.pos.pre_block_logic(block)
  File "/home/lenij/crypto/QRL/qrl/core/node.py", line 420, in pre_block_logic
    if not self.chain.block_chain_buffer.add_block(block):
  File "/home/lenij/crypto/QRL/qrl/core/ChainBuffer.py", line 239, in add_block
    self.move_to_mainchain(blocknum - config.dev.reorg_limit)
  File "/home/lenij/crypto/QRL/qrl/core/ChainBuffer.py", line 463, in move_to_mainchain
    if not self.state.state_add_block(self.chain, block):
  File "/home/lenij/crypto/QRL/qrl/core/state.py", line 200, in state_add_block
    nonce = self.stake_validators_list.sv_list[block.transactions[0].txto].nonce
KeyError: 'Qebe26789cc7d17e84bfd4c239c0fef378d1afba427b83443dddf7d70afc3708a647bd4c8'

**Comment by cyyber** [comment]
Fix for this issue is being tested.

**Comment by cyyber** [comment]
Issue fixed in PR #434
