### ISSUE TITLE
ChainBuffer.py | TypeError: __init__() got an unexpected keyword argument 'pool_size'

### ISSUE THREAD

**Issue by moplk** [theQRL/QRL#352]
(fresh node on a raspberry pi)
```
2017-10-09 15:50:47,451 |unsynced| INFO : Creating new chain file
2017-10-09 15:50:47,452 |unsynced| INFO : Loading genesis from /home/thomas/QRL/qrl/core/genesis.yml
2017-10-09 15:50:47,465 |unsynced| INFO : genesis:
2017-10-09 15:50:47,469 |unsynced| CRITICAL : Unhandled exception!
Traceback (most recent call last):
  File "start_qrl.py", line 13, in <module>
    main()
  File "/home/thomas/QRL/qrl/main.py", line 105, in main
    chain_obj.m_load_chain()
  File "/home/thomas/QRL/qrl/core/chain.py", line 601, in m_load_chain
    self.load_chain_by_epoch(0)
  File "/home/thomas/QRL/qrl/core/chain.py", line 453, in load_chain_by_epoch
    self.block_chain_buffer = ChainBuffer(self)
  File "/home/thomas/QRL/qrl/core/ChainBuffer.py", line 30, in __init__
    self.assign_slave_xmsspool(0)
  File "/home/thomas/QRL/qrl/core/ChainBuffer.py", line 47, in assign_slave_xmsspool
    pool_size = 2)
TypeError: __init__() got an unexpected keyword argument 'pool_size'
```

**Comment by cyyber** [comment]
A fix is being tested. There are still some other bugs, the fix for this bug will be included in that.

**Comment by cyyber** [comment]
Please check the swig version on your node by following command
swig -version

Make sure you have SWIG Version atleast 3.0.10

**Comment by moplk** [comment]
SWIG version was/is 3.0.2. Let me know if I can help test something.
```
thomas@volta:~/QRL$ swig3.0 -version
SWIG Version 3.0.2
Compiled with g++ [armv7l-unknown-linux-gnueabihf]
Configured options: +pcre
Please see http://www.swig.org for reporting bugs and further information
```

**Comment by jleni** [comment]
As similar issue was detected in Debian Jessie.
The updated instructions in https://github.com/theQRL/QRL/blob/master/README.md should fix your problem. 

I have update the instructions and tested in Debian Jessie. Maybe after the hard-fork once testnet is running again, you can test the new instructions in Raspbian Jessie.

**Comment by moplk** [comment]
I think #369 fixed this for me.

My node is on a jessie based os, indeed. I tried undoing the jessie specific instructions. It seems the regular swig3.0 package works as well.

**Comment by jleni** [comment]
@moplk Yes, #369 fixes the problem but it is more like a workaround. By following jessie instructions we ensure that you are running newer swig and cmake versions (which bring a lot of additional fixes)

I am closing this issue.
