### ISSUE TITLE
0.53.0a telnet wallet command

### ISSUE THREAD

**Issue by FL-Riko** [theQRL/QRL#374]
as long grpc ist not implemented, telnet command wallet should work,

but for a unsynced node following error occurs:

2017-10-12 18:36:56,760 |syncing| CRITICAL : [TWISTED] Unhandled Error
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/pi/QRL/qrl/core/walletprotocol.py", line 95, in dataReceived
    if not self.parse_cmd(data):
  File "/home/pi/QRL/qrl/core/walletprotocol.py", line 76, in parse_cmd
    self.cmd_mapping[command](args)
  File "/home/pi/QRL/qrl/core/walletprotocol.py", line 278, in _wallet
    self.factory.chain.transaction_pool, True)
  File "/home/pi/QRL/qrl/core/wallet.py", line 160, in list_addresses
    tmp_state_balance = state.state_balance(addr_bundle.address)
  File "/home/pi/QRL/qrl/core/state.py", line 155, in state_balance
    nonce, balance, pubhash_list = self._get_address_state(addr)
  File "/home/pi/QRL/qrl/core/state.py", line 394, in _get_address_state
    data = self.db.get_raw(address.encode())
  File "/home/pi/QRL/qrl/core/db.py", line 67, in get_raw
    return self.db.Get(key)
builtins.KeyError:

**Comment by FL-Riko** [comment]
for a synced mode it works

**Comment by FL-Riko** [comment]
got same error from above for two adresses
