### ISSUE TITLE
0.53.0a unexpected exception leads to forked node

### ISSUE THREAD

**Issue by FL-Riko** [theQRL/QRL#378]
2017-10-13 20:29:20,985 |synced| DEBUG : -->>FBHL called
2017-10-13 20:29:36,032 |synced| ERROR : select_best_bkmr Unexpected Exception
2017-10-13 20:29:36,035 |synced| ERROR : 'ba6a349dd90dbb94eac47ddfa827389310f988c31738d3b2a90ff6e56d85eea7'
2017-10-13 20:29:38,250 |synced| INFO : 52.220.119.253 disconnected. remainder connected: 8
2017-10-13 20:29:38,254 |synced| DEBUG : connection lost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-cle
an fashion.
]
2017-10-13 20:29:38,648 |synced| INFO : 104.251.219.145 disconnected. remainder connected: 7
2017-10-13 20:29:38,652 |synced| DEBUG : connection lost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
2017-10-13 20:29:38,657 |synced| INFO : 104.251.219.40 disconnected. remainder connected: 6
2017-10-13 20:29:38,661 |synced| DEBUG : connection lost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
2017-10-13 20:29:38,665 |synced| INFO : 104.237.3.185 disconnected. remainder connected: 5
2017-10-13 20:29:38,669 |synced| DEBUG : connection lost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
2017-10-13 20:29:38,674 |synced| INFO : 104.237.3.184 disconnected. remainder connected: 4
2017-10-13 20:29:38,678 |synced| DEBUG : connection lost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
2017-10-13 20:29:41,051 |synced| CRITICAL : [TWISTED] Unhandled Error
Traceback (most recent call last):
  File "start_qrl.py", line 13, in <module>
    main()
  File "/home/pi/QRL/qrl/main.py", line 141, in main
    reactor.run()
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/pi/QRL/qrl/core/p2pfactory.py", line 84, in RFM
    peers_list = self.master_mr.requested_hash[msg_hash_str].peers_connection_list
builtins.KeyError: 'ba6a349dd90dbb94eac47ddfa827389310f988c31738d3b2a90ff6e56d85eea7'

2017-10-13 20:29:41,057 |synced| CRITICAL : [TWISTED] Unhandled Error
Traceback (most recent call last):
  File "start_qrl.py", line 13, in <module>
    main()
  File "/home/pi/QRL/qrl/main.py", line 141, in main
    reactor.run()
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/pi/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/pi/QRL/qrl/core/p2pfactory.py", line 84, in RFM
    peers_list = self.master_mr.requested_hash[msg_hash_str].peers_connection_list
builtins.KeyError: 'ba6a349dd90dbb94eac47ddfa827389310f988c31738d3b2a90ff6e56d85eea7'

**Comment by cyyber** [comment]
Please also provide qrl.log. You may attach it here or send me in discord.

**Comment by FL-Riko** [comment]
error time was 2017-10-13 20:29:41,057

**Comment by FL-Riko** [comment]
qrl.log via discord

**Comment by cyyber** [comment]
PR #380 expected to fix the actual cause of this problem. I will keep this issue open for few more days, to ensure that you should not face this same problem again.

**Comment by cyyber** [comment]
PR #380 tested and is working fine. No ping timeout has been noticed which was causing fork.
