### ISSUE TITLE
0.53.1a p2pprotocol, multiple error for blocknumber

### ISSUE THREAD

**Issue by FL-Riko** [theQRL/QRL#385]
2017-10-14 23:35:30,792 |synced| DEBUG : Sending PING to 158.69.79.24:9000
2017-10-14 23:35:30,885 |synced| INFO : >>>Received block from 104.237.3.185:9000 5916 Q321551228be4c8275bc3a2665347f4b399216268bf6a704c6fd5ced5666c117105f82613
2017-10-14 23:35:31,144 |synced| DEBUG : BLOCK: 5913 epoch: 59 blocks_left: 86 nonce: 2 stake_selector Q1164abe0aeb3d8026986309ecadace30b45e0def644ecb0ba71e3491a2e8a5ab408f69dc
2017-10-14 23:35:31,264 |synced| DEBUG : 7b2f035f7422910194e9e648062582a6c847e3188688b205a9bb6abf8c7816ea 2 tx passed verification.
2017-10-14 23:35:34,482 |synced| INFO : [ChainBuffer] Block #5916 added  stake: Q321551228be4c8275bc3a2665347f4b399216268bf6a704c6fd5ced5666c117105f82613
2017-10-14 23:35:34,741 |synced| DEBUG : Received PONG from 104.237.3.185:9000
2017-10-14 23:35:34,744 |synced| DEBUG : Sending PING to 52.220.119.253:9000
2017-10-14 23:35:34,796 |synced| ERROR : executing [PBHL]
2017-10-14 23:35:34,799 |synced| ERROR : Traceback (most recent call last):
  File "/home/pi/QRL/qrl/core/p2pprotocol.py", line 82, in parse_msg
    func()
TypeError: PBHL() missing 1 required positional argument: 'blocknumber'

2017-10-14 23:35:35,518 |synced| DEBUG : Received PONG from 104.237.3.184:9000
2017-10-14 23:35:49,256 |synced| INFO : <<<Sending blockheight and headerhash to: 77.59.180.49 1508016949.2566955
2017-10-14 23:35:50,027 |synced| DEBUG : Sending PING to 77.59.180.49:55704

**Comment by FL-Riko** [comment]
2nd error

2017-10-15 01:04:49,002 |synced| ERROR : executing [EBHL]
2017-10-15 01:04:49,004 |synced| ERROR : Traceback (most recent call last):
  File "/home/pi/QRL/qrl/core/p2pprotocol.py", line 80, in parse_msg
    func(jdata['data'])
  File "/home/pi/QRL/qrl/core/p2pprotocol.py", line 161, in EBHL
    if blocknum_headerhash[blocknum] != block.blockheader.headerhash:
AttributeError: 'list' object has no attribute 'blockheader'

2017-10-15 01:04:49,035 |synced| DEBUG : -->>EBHL received
2017-10-15 01:04:49,038 |synced| DEBUG : -->>EBHL processing
2017-10-15 01:04:49,040 |synced| ERROR : executing [EBHL]
2017-10-15 01:04:49,044 |synced| ERROR : Traceback (most recent call last):
  File "/home/pi/QRL/qrl/core/p2pprotocol.py", line 80, in parse_msg
    func(jdata['data'])
  File "/home/pi/QRL/qrl/core/p2pprotocol.py", line 149, in EBHL
    blocknum = min(blocknum_headerhash)
ValueError: min() arg is an empty sequence

2017-10-15 01:04:49,052 |synced| DEBUG : -->>EBHL received
2017-10-15 01:04:49,053 |synced| DEBUG : -->>EBHL processing
2017-10-15 01:04:49,055 |synced| ERROR : executing [EBHL]
2017-10-15 01:04:49,058 |synced| ERROR : Traceback (most recent call last):
  File "/home/pi/QRL/qrl/core/p2pprotocol.py", line 80, in parse_msg
    func(jdata['data'])
  File "/home/pi/QRL/qrl/core/p2pprotocol.py", line 149, in EBHL
    blocknum = min(blocknum_headerhash)
ValueError: min() arg is an empty sequence

**Comment by FL-Riko** [comment]
finally node get a forked one

qrl.log via discord

**Comment by FL-Riko** [comment]
new additional error for keyerror: "blocknumber"

2017-10-23 20:37:32,605 |unsynced| ERROR : executing [CB]
2017-10-23 20:37:32,632 |unsynced| ERROR : Traceback (most recent call last):
  File "/home/pi/QRL/qrl/core/p2pprotocol.py", line 80, in parse_msg
    func(jdata['data'])
  File "/home/pi/QRL/qrl/core/p2pprotocol.py", line 632, in CB
    block_number = z['block_number']
KeyError: 'block_number'

**Comment by cyyber** [comment]
The above bugs has been fixed from 0.54.2.
