### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by converghub** [theQRL/QRL#502]
Here is the log file with Raspberry Pi 3. https://transfer.sh/d805E/qrl.log
```
2017-10-26 20:49:24,860 |syncing| ERROR : Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/qrl/core/block.py", line 157, in validate_block
    if not self._validate_tx_in_block(chain):
  File "/home/pi/.local/lib/python3.5/site-packages/qrl/core/block.py", line 172, in _validate_tx_in_block
    valid = coinbase_txn.validate_extended(sv_list=sv_list, blockheader=self.blockheader)
  File "/home/pi/.local/lib/python3.5/site-packages/qrl/core/Transaction.py", line 478, in validate_extended
    if blockheader.blocknumber > 1 and sv_list[self.txto].slave_public_key != self.PK:
TypeError: 'NoneType' object is not subscriptable
```
Raspbian's version:
```
pi@raspberrypi:~/.qrl $ uname -a
Linux raspberrypi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux
pi@raspberrypi:~/.qrl $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.1 (stretch)
Release:        9.1
Codename:       stretch
```

**Comment by converghub** [comment]
With the latest code base, QRL blockchain ledger 0.54.5, it doesn't occur such things currently...
Sorry for the confusions. I'll see how it goes for a few days.
