### ISSUE TITLE
Just Upgraded -  2017-12-24 21:55:42,207|0.58.3|synced| CRITICAL : [TWISTED] Unhandled Error

### ISSUE THREAD

**Issue by galations522** [theQRL/QRL#753]
2017-12-24 21:54:12,478|0.58.3|synced| CRITICAL : [TWISTED] Unhandled Error
Traceback (most recent call last):
  File "/home/dir/.local/lib/python3.5/site-packages/qrl/main.py", line 127, in main
    start_legacy_services(buffered_chain, qrlnode, sync_state)
  File "/home/dir/.local/lib/python3.5/site-packages/qrl/main.py", line 84, in start_legacy_services
    reactor.run()
  File "/home/dir/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/home/dir/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/dir/.local/lib/python3.5/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/dir/.local/lib/python3.5/site-packages/qrl/core/node.py", line 505, in post_block_logic
    self.create_next_block(blocknumber, activation_blocknumber)
  File "/home/dir/.local/lib/python3.5/site-packages/qrl/core/node.py", line 429, in create_next_block
    hash_chain = self.buffered_chain.hash_chain_get(blocknumber)
  File "/home/dir/.local/lib/python3.5/site-packages/qrl/core/BufferedChain.py", line 1206, in hash_chain_get
    return self.hash_chain[epoch]
builtins.KeyError: 253

**Comment by cyyber** [comment]
Buffered Chain removed in PoW
