### ISSUE TITLE
gRPC GetObject Issue

### ISSUE THREAD

**Issue by scottdonaldau** [theQRL/QRL#773]
I have noticed the following issue affecting the GetObject gRPC API.

Immediately after sending a transaction into the network, and receiving confirmation it's now in a block, I am able to run GetObject by sending the transaction hash and receive a response.

Shortly after (maybe 30 seconds), I start to see the following error on the node for about 30 seconds if I continually try and request the transaction hash.

```
2018-01-12 21:54:12,562|0.58.4|synced| DEBUG : [PublicAPI] GetObject
2018-01-12 21:54:12,563|0.58.4|synced| ERROR : Traceback (most recent call last):
  File "/root/QRL/qrl/services/grpcHelper.py", line 20, in wrap_f
    return f(caller_self, request, context)
  File "/root/QRL/qrl/services/PublicAPIService.py", line 150, in GetObject
    block_index = self.qrlnode.get_blockidx_from_txhash(transaction.txhash)
AttributeError: 'Transaction' object has no attribute 'txhash'
```

Shortly after this again (maybe another 30 seconds), it responds as normal.

**Comment by scottdonaldau** [comment]
This issue is no longer present. Closing.
